22 get url from cloudinary and insert it into formular
DunjaWohlers/product-gallery pull request #50
Opened 2022-08-25 08:03 UTC by DunjaWohlers

2022-08-29 13:38 UTC, alanmiste requested changes
Ich schlage vor, die Bilder für die Schaltflächen durch Elemente aus MUI oder React Icon zu ersetzen, zum Beispiel:
backend/src/test/resources/sawIcon.png
seine Größe beträgt 330 KB.
Ich fand auch eine Mischung aus Englisch und Deutsch 😅

2022-08-29 13:38 UTC, alanmiste commented on backend/src/main/java/de/neuefische/cgnjava222/productgallery/controller/FileUploadController.java
> +    @PostMapping("/uploadFile/")
brauchest du "/" nach dem Pfad?

2022-08-29 13:38 UTC, alanmiste commented on backend/src/main/java/de/neuefische/cgnjava222/productgallery/service/FileService.java
> +            var responseObj = cloudinary.uploader().upload(newFile, ObjectUtils.emptyMap());
var !!

2022-08-29 13:38 UTC, alanmiste commented on frontend/src/component/DetailsProduct.tsx
> +                {thisProduct && <p><img src={thisProduct.pictureObj[0].url} alt={"Loading..."}/></p>}
Anstelle der ganzen " thisProduct && " kann man beim Root-Element auf eines verzichten, oder?!

2022-08-29 13:38 UTC, alanmiste commented on frontend/src/type/PicObj.ts
> +}
Leerzeile umbruch?

2022-08-30 05:39 UTC, DunjaWohlers commented on backend/src/main/java/de/neuefische/cgnjava222/productgallery/service/FileService.java
> +            var responseObj = cloudinary.uploader().upload(newFile, ObjectUtils.emptyMap());
schön, was ;)?

2022-08-30 05:46 UTC, merged